import http from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),publicDir=path.join(root,"public"),port=Number(process.env.PORT||3210),host=process.env.HOST||"127.0.0.1";
const files={"/":"suixinglu.html","/suixinglu.html":"suixinglu.html","/suixinglu-login.html":"suixinglu-login.html","/suixinglu.css":"suixinglu.css","/suixinglu-enhance.css":"suixinglu-enhance.css","/suixinglu.js":"suixinglu.js","/suixinglu-extra.js":"suixinglu-extra.js","/suixinglu-splash.js":"suixinglu-splash.js","/manifest.webmanifest":"manifest.webmanifest","/sw.js":"sw.js","/icons/icon.svg":"icons/icon.svg"};
const mime=n=>n.endsWith(".html")?"text/html":n.endsWith(".css")?"text/css":n.endsWith(".js")?"text/javascript":n.endsWith(".svg")?"image/svg+xml":n.endsWith(".webmanifest")?"application/manifest+json":"application/octet-stream";
export const server=http.createServer(async(req,res)=>{const url=new URL(req.url,"http://localhost");if(url.pathname==="/api/health"){res.writeHead(200,{"Content-Type":"application/json; charset=utf-8"});return res.end('{"ok":true,"app":"随行录"}')}const name=files[url.pathname];if(!name){res.writeHead(404,{"Content-Type":"application/json; charset=utf-8"});return res.end('{"error":"Not found"}')}try{const data=await readFile(path.join(publicDir,name));res.writeHead(200,{"Content-Type":`${mime(name)}; charset=utf-8`,"Cache-Control":name.endsWith(".html")?"no-cache":"public, max-age=3600"});res.end(data)}catch(error){res.writeHead(500,{"Content-Type":"application/json; charset=utf-8"});res.end(JSON.stringify({error:error.message}))}});
if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(port,host,()=>console.log(`随行录已启动：http://${host}:${port}`));
